export const styles = {
  wrapper: {
    background: '#ffffff',
    border: '1px solid #e7ecf3',
    borderRadius: '20px',
    padding: '32px',
    marginBottom: '24px',
    boxShadow: '0 12px 32px rgba(15, 23, 42, 0.06)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: '16px',
    marginBottom: '28px',
    paddingBottom: '20px',
    borderBottom: '1px solid #eef2f7',
  },
  headerBadge: {
    background: '#f3f7f5',
    color: '#1f6f43',
    border: '1px solid #cfe7d7',
    borderRadius: '999px',
    padding: '8px 14px',
    fontSize: '12px',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  title: {
    margin: 0,
    marginBottom: '8px',
    fontSize: '30px',
    lineHeight: 1.1,
    fontWeight: 700,
    color: '#101828',
  },
  subtitle: {
    margin: 0,
    color: '#667085',
    fontSize: '14px',
    lineHeight: 1.5,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  section: {
    background: '#ffffff',
    border: '1px solid #edf2f7',
    borderRadius: '18px',
    padding: '22px',
  },
  sectionSoft: {
    background: '#f8fafc',
    border: '1px solid #e6edf5',
    borderRadius: '18px',
    padding: '22px',
  },
  sectionHeader: {
    marginBottom: '18px',
  },
  sectionTitle: {
    margin: 0,
    marginBottom: '6px',
    fontSize: '18px',
    fontWeight: 700,
    color: '#24324a',
  },
  sectionText: {
    margin: 0,
    color: '#667085',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))',
    gap: '18px',
  },
  gridSingle: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '18px',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#344054',
  },
  input: {
    minHeight: '46px',
    borderRadius: '10px',
    border: '1px solid #d0d5dd',
    padding: '0 14px',
    fontSize: '14px',
    color: '#101828',
    background: '#ffffff',
  },
  textarea: {
    minHeight: '120px',
    borderRadius: '10px',
    border: '1px solid #d0d5dd',
    padding: '12px 14px',
    fontSize: '14px',
    color: '#101828',
    resize: 'vertical',
    background: '#ffffff',
  },
  helper: {
    fontSize: '12px',
    color: '#667085',
    lineHeight: 1.4,
  },
  error: {
    fontSize: '12px',
    color: '#b42318',
  },
  statusCards: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(200px, 100%), 1fr))',
    gap: '14px',
  },
  choiceCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    border: '1px solid #dbe4ee',
    borderRadius: '14px',
    padding: '14px 16px',
    fontSize: '14px',
    color: '#344054',
    background: '#ffffff',
  },
  alertWarning: {
    border: '1px solid #fecd70',
    borderRadius: '14px',
    padding: '14px 16px',
    background: '#fffaeb',
    color: '#7a2e0f',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  alertInfo: {
    border: '1px solid #b2ddff',
    borderRadius: '14px',
    padding: '14px 16px',
    background: '#eff8ff',
    color: '#175cd3',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  alertList: {
    margin: '8px 0 0',
    paddingLeft: '18px',
  },
  vacinasBloco: {
    display: 'grid',
    gap: '14px',
  },
  groupTitle: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 700,
    color: '#24324a',
  },
  vacinaCardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(260px, 100%), 1fr))',
    gap: '14px',
  },
  vacinaCard: {
    display: 'grid',
    gap: '12px',
    border: '1px solid #dbe4ee',
    borderRadius: '16px',
    padding: '16px',
    background: '#ffffff',
  },
  vacinaCardChecked: {
    borderColor: '#84ca9d',
    boxShadow: '0 0 0 1px rgba(31, 111, 67, 0.15)',
    background: '#f6fef9',
  },
  vacinaTop: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'center',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '999px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 700,
  },
  badgeEssencial: {
    background: '#dcfce7',
    color: '#166534',
  },
  badgeComplementar: {
    background: '#e0f2fe',
    color: '#0c4a6e',
  },
  vacinaMeta: {
    display: 'grid',
    gap: '10px',
  },
  vacinaLabel: {
    fontSize: '11px',
    color: '#667085',
    textTransform: 'uppercase',
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  vacinaValue: {
    fontSize: '14px',
    color: '#101828',
    fontWeight: 600,
  },
  vacinaDescricao: {
    fontSize: '13px',
    color: '#344054',
    lineHeight: 1.5,
  },
  vacinaDetalhamento: {
    fontSize: '12px',
    color: '#667085',
    lineHeight: 1.5,
  },
  alertError: {
    border: '1px solid #fecdca',
    borderRadius: '14px',
    padding: '14px 16px',
    background: '#fef3f2',
    color: '#b42318',
    fontSize: '13px',
  },
  alertSuccess: {
    border: '1px solid #abefc6',
    borderRadius: '14px',
    padding: '14px 16px',
    background: '#ecfdf3',
    color: '#067647',
    fontSize: '13px',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: '12px',
  },
  secondaryButton: {
    minHeight: '46px',
    borderRadius: '10px',
    border: '1px solid #d0d5dd',
    padding: '0 18px',
    background: '#ffffff',
    color: '#344054',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  button: {
    minHeight: '46px',
    borderRadius: '10px',
    border: 'none',
    padding: '0 18px',
    background: '#1f6f43',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
  },
};
