export const styles = {
  page: { display: 'flex', flexDirection: 'column', gap: '24px' },
  section: { background: '#ffffff', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '24px' },
  sectionHeader: { marginBottom: '18px' },
  sectionTitle: { margin: 0, marginBottom: '6px', fontSize: '22px', color: '#111827' },
  sectionSubtitle: { margin: 0, color: '#6b7280', fontSize: '14px' },
  grid4: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(210px, 100%), 1fr))', gap: '16px' },
  metricCard: { background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '18px', display: 'flex', flexDirection: 'column', gap: '8px' },
  metricTitle: { fontSize: '13px', color: '#6b7280', fontWeight: 600 },
  metricValue: { fontSize: '28px', color: '#111827', lineHeight: 1 },
  metricSubtitle: { fontSize: '13px', color: '#4b5563' },
  alertCard: { background: '#fff7ed', border: '1px solid #fdba74', borderRadius: '8px', padding: '18px', display: 'flex', flexDirection: 'column', gap: '10px' },
  alertTitle: { fontSize: '14px', color: '#9a3412', fontWeight: 700 },
  alertValue: { fontSize: '28px', color: '#9a3412' },
  statusGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(180px, 100%), 1fr))', gap: '16px' },
  statusCard: { background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' },
  statusLabel: { fontSize: '13px', color: '#6b7280', fontWeight: 600 },
  statusValue: { fontSize: '24px', color: '#111827' },
  twoColumns: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))', gap: '16px', marginTop: '18px' },
  miniTableCard: { border: '1px solid #e5e7eb', borderRadius: '8px', padding: '16px', background: '#ffffff' },
  miniTableTitle: { margin: '0 0 12px', color: '#111827', fontSize: '16px' },
  methodBox: { marginTop: '14px', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '12px', display: 'grid', gap: '6px', color: '#4b5563', fontSize: '13px', lineHeight: 1.5 },
  filterField: { display: 'grid', gap: '6px', maxWidth: '360px', marginBottom: '16px', color: '#374151', fontSize: '13px', fontWeight: 700 },
  filterInput: { height: '42px', border: '1px solid #d1d5db', borderRadius: '8px', padding: '0 12px', fontSize: '14px', background: '#ffffff' },
  note: { margin: '12px 0 0', color: '#6b7280', fontSize: '13px', lineHeight: 1.5 },
  tableWrapper: { overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { textAlign: 'left', padding: '12px', borderBottom: '1px solid #e5e7eb', fontSize: '14px', whiteSpace: 'nowrap' },
  td: { padding: '12px', borderBottom: '1px solid #f3f4f6', fontSize: '14px' },
};
