import { PERMISSIONS } from '../../../utils/permissions';

export const licenciamentoAdminNavigation = [
  { key: 'dashboard', label: 'Dashboard', permission: PERMISSIONS.LICENCIAMENTO_DASHBOARD_VIEW },
  { key: 'processos', label: 'Processos', permission: PERMISSIONS.LICENCIAMENTO_PROCESSOS_VIEW },
  { key: 'novo', label: 'Novo processo', permission: PERMISSIONS.LICENCIAMENTO_PROCESSOS_CREATE },
  { key: 'parametros', label: 'Parâmetros', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d1', label: 'Parametrizacao Fase 2D.1', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d2', label: 'Parametrizacao Fase 2D.2', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d21', label: 'Parametrizacao Fase 2D.2.1', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d3', label: 'Mapa Mestre Fase 2D.3', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d4a', label: 'Conferencia Grupo 19 2D.4-A', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d4b', label: 'Parametrizacao Grupo 19 2D.4-B', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d5a', label: 'Mapa Pos-Grupo 19 2D.5-A', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d5b', label: 'Complementacao Controlada 2D.5B', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d5c', label: 'Grupo 21 - Conferencia 2D.5C', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d5c1', label: 'Grupo 21 - Conferencia Visual 2D.5C.1', permission: PERMISSIONS.LICENCIAMENTO_PARAMETROS_VIEW },
  { key: 'parametrizacao2d5c2', label: 'Grupo 21 - Bancada de Conferência 2D.5C.2', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c2a', label: 'Grupo 21 - Prévia de Seed 2D.5C.2-A', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c2b', label: 'Grupo 21 - Importação de Conferência 2D.5C.2-B', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_IMPORT_VIEW },
  { key: 'parametrizacao2d5c2c', label: 'Grupo 21 - Preparação Matriz Real 2D.5C.2-C', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c3a', label: 'Grupo 21 - Conferência Complementar 2D.5C.3-A', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c3b', label: 'Grupo 21 - Bloqueio Normativo 2D.5C.3-B', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c4', label: 'Grupo 21 — Revisão Normativa 2D.5C.4', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'parametrizacao2d5c5', label: 'Grupo 21 — Seed Controlado 2D.5C.5', permission: PERMISSIONS.LICENCIAMENTO_PARAMETRIZACAO_CONFERENCIA_VIEW },
  { key: 'assistenteAnalises', label: 'Analises do Assistente', permission: PERMISSIONS.LICENCIAMENTO_ASSISTENTE_VIEW },
  { key: 'preRequerimentos', label: 'Pre-Requerimentos', permission: PERMISSIONS.LICENCIAMENTO_PRE_REQUERIMENTO_VIEW },
  { key: 'governanca', label: 'Governanca normativa', permission: PERMISSIONS.LICENCIAMENTO_GOVERNANCA_NORMATIVA_VIEW },
  { key: 'homologacao', label: 'Homologacao assistida', permission: PERMISSIONS.LICENCIAMENTO_HOMOLOGACAO_ASSISTIDA_VIEW },
  { key: 'fechamento', label: 'Fechamento de Homologacao', permission: PERMISSIONS.LICENCIAMENTO_HOMOLOGACAO_FECHAMENTO_VIEW },
  { key: 'checklist', label: 'Checklist Assistido', permission: PERMISSIONS.LICENCIAMENTO_CHECKLIST_ASSISTIDO_VIEW },
];

export const licenciamentoLayoutConfig = {
  moduleKey: 'licenciamento',
  platformName: 'Plataforma SIGMA',
  brandBadge: 'LIC',
  brandSub: 'Módulo de Licenciamento Ambiental da Plataforma SIGMA',
  pageTitle: 'Licenciamento Ambiental',
  pageSubtitle: 'Gestão inicial de processos, requerentes, empreendimentos, parâmetros e enquadramento',
  environmentLabel: 'Área interna SMAD',
  portalButtonLabel: 'Portal SIGMA',
  publicButtonLabel: 'Painel SIGMA',
  logoutButtonLabel: 'Sair',
  footerText: 'SMAD - Plataforma SIGMA / Licenciamento Ambiental',
  menuItems: licenciamentoAdminNavigation,
  showPortalShortcut: false,
  showPublicShortcut: false,
  theme: {
    appBackground: '#eef5ff',
    mainBackground: '#eef5ff',
    contentBackground: 'linear-gradient(180deg, #eef5ff 0%, #f8fbff 42%, #eef5ff 100%)',
    sidebarBackground: 'linear-gradient(180deg, #0d1b3d 0%, #0d3f8f 100%)',
    sidebarBorder: '#0d3f8f',
    sidebarDivider: 'rgba(255, 255, 255, 0.16)',
    sidebarShadow: '8px 0 24px rgba(13, 27, 61, 0.12)',
    brandBackground: '#1e5cc8',
    brandColor: '#ffffff',
    brandShadow: '0 10px 22px rgba(30, 92, 200, 0.28)',
    brandSubColor: '#dceaff',
    footerColor: '#dceaff',
    headerBackground: 'rgba(255, 255, 255, 0.94)',
    headerBorder: '#d8e5f2',
    headerShadow: '0 8px 24px rgba(13, 63, 143, 0.06)',
    titleColor: '#0d1b3d',
    subtitleColor: '#5f6f83',
    accent: '#1e5cc8',
    infoBackground: '#eff6ff',
    infoBorder: '#cfe0f5',
    infoColor: '#0d3f8f',
    controlBackground: '#ffffff',
    controlBorder: '#cfe0f5',
    controlColor: '#0d1b3d',
    navBackground: 'rgba(255, 255, 255, 0.08)',
    navBorder: 'rgba(255, 255, 255, 0.14)',
    navColor: '#f4f9ff',
    navActiveBackground: '#ffffff',
    navActiveBorder: '#ffffff',
    navActiveColor: '#0d3f8f',
    navActiveShadow: '0 12px 24px rgba(0, 0, 0, 0.16)',
  },
};
