export const styles = {
  page: {
    minHeight: '100vh',
    background: '#f3f4f6',
    padding: 'clamp(12px, 4vw, 24px)',
    display: 'grid',
    gap: '18px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '16px',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    background: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: 'clamp(16px, 4vw, 24px)',
  },
  headerActions: { display: 'flex', gap: '10px', flexWrap: 'wrap' },
  badge: {
    display: 'inline-flex',
    background: '#111827',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '8px 12px',
    fontWeight: 700,
    marginBottom: '12px',
  },
  title: { margin: 0, fontSize: '28px', color: '#111827' },
  subtitle: { margin: '8px 0 0', color: '#4b5563', lineHeight: 1.5, fontSize: '14px' },
  section: {
    background: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: 'clamp(16px, 4vw, 24px)',
    display: 'grid',
    gap: '16px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  sectionTitle: { margin: 0, fontSize: '22px', color: '#111827' },
  portalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))',
    gap: '24px',
    alignItems: 'start',
  },
  mobileHub: {
    background: '#ffffff',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: 'clamp(14px, 4vw, 20px)',
    display: 'grid',
    gap: '14px',
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(140px, 100%), 1fr))',
    gap: '10px',
  },
  summaryCard: {
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '4px',
    background: '#f9fafb',
    color: '#374151',
  },
  quickActions: { display: 'flex', flexWrap: 'wrap', gap: '10px' },
  animalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))',
    gap: '12px',
  },
  animalCard: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '14px',
    display: 'grid',
    gap: '8px',
    color: '#374151',
    background: '#ffffff',
    fontSize: '14px',
  },
  detailPanel: {
    background: '#ffffff',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: 'clamp(16px, 4vw, 24px)',
    display: 'grid',
    gap: '16px',
  },
  detailContent: { display: 'grid', gap: '14px' },
  detailBlock: {
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    background: '#ffffff',
    color: '#374151',
    fontSize: '14px',
  },
  detailTitle: { margin: 0, fontSize: '16px', color: '#111827' },
  timeline: { display: 'grid', gap: '8px' },
  timelineItem: {
    borderLeft: '3px solid #1f6f43',
    padding: '4px 0 4px 10px',
    display: 'grid',
    gap: '3px',
    color: '#374151',
    fontSize: '14px',
  },
  nextStepBox: {
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    background: '#eff6ff',
    color: '#1e3a8a',
    padding: '12px',
    display: 'grid',
    gap: '4px',
    fontSize: '14px',
  },
  offlineBanner: {
    border: '1px solid #fcd34d',
    borderRadius: '8px',
    background: '#fffbeb',
    color: '#92400e',
    padding: '12px',
    fontSize: '14px',
  },
  updateBanner: {
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    background: '#eff6ff',
    color: '#1d4ed8',
    padding: '12px',
    fontSize: '14px',
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  syncMeta: { margin: 0, color: '#6b7280', fontSize: '13px' },
  tabs: { display: 'flex', gap: '10px' },
  tab: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    background: '#ffffff',
    padding: '9px 12px',
    cursor: 'pointer',
    fontWeight: 700,
    color: '#374151',
  },
  tabActive: {
    border: '1px solid #1f6f43',
    borderRadius: '8px',
    background: '#1f6f43',
    padding: '9px 12px',
    cursor: 'pointer',
    fontWeight: 700,
    color: '#ffffff',
  },
  form: { display: 'grid', gap: '14px' },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))',
    gap: '14px',
  },
  field: { display: 'grid', gap: '6px' },
  label: { color: '#374151', fontSize: '13px', fontWeight: 700 },
  hint: { margin: 0, color: '#6b7280', fontSize: '13px' },
  input: {
    minHeight: '46px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '0 12px',
    fontSize: '16px',
    background: '#ffffff',
  },
  textarea: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '16px',
    resize: 'vertical',
    background: '#ffffff',
  },
  checkboxGroup: {
    display: 'grid',
    gap: '8px',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '12px',
    background: '#ffffff',
  },
  checkbox: { display: 'flex', alignItems: 'center', gap: '8px', color: '#374151', fontSize: '14px' },
  primaryButton: {
    minHeight: '46px',
    border: 'none',
    borderRadius: '8px',
    background: '#1f6f43',
    color: '#ffffff',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 16px',
  },
  secondaryButton: {
    minHeight: '46px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    background: '#ffffff',
    color: '#334155',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 14px',
  },
  installButton: {
    minHeight: '46px',
    border: '1px solid #111827',
    borderRadius: '8px',
    background: '#111827',
    color: '#ffffff',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 16px',
  },
  alertError: {
    border: '1px solid #fecaca',
    borderRadius: '8px',
    background: '#fef2f2',
    color: '#b91c1c',
    padding: '12px',
    fontSize: '14px',
  },
  alertSuccess: {
    border: '1px solid #bbf7d0',
    borderRadius: '8px',
    background: '#f0fdf4',
    color: '#166534',
    padding: '12px',
    fontSize: '14px',
  },
  resetBox: { border: '1px solid #e5e7eb', borderRadius: '8px', padding: '14px', display: 'grid', gap: '14px' },
  textButton: {
    border: 'none',
    background: 'transparent',
    color: '#1f6f43',
    cursor: 'pointer',
    fontWeight: 700,
    justifySelf: 'start',
    padding: 0,
  },
  cards: { display: 'grid', gap: '12px' },
  cardActions: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '4px' },
  asideBlock: { display: 'grid', gap: '12px', borderBottom: '1px solid #e5e7eb', paddingBottom: '16px', marginBottom: '4px' },
  followCard: {
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    color: '#374151',
    fontSize: '14px',
  },
  notificationCard: {
    border: '1px solid #bbf7d0',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    color: '#166534',
    background: '#f0fdf4',
    fontSize: '14px',
  },
  notificationRead: {
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    color: '#4b5563',
    background: '#ffffff',
    fontSize: '14px',
  },
  notificationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  statusPill: {
    borderRadius: '8px',
    background: '#166534',
    color: '#ffffff',
    padding: '4px 8px',
    fontSize: '12px',
    fontWeight: 700,
  },
  statusPillMuted: {
    borderRadius: '8px',
    background: '#e5e7eb',
    color: '#4b5563',
    padding: '4px 8px',
    fontSize: '12px',
    fontWeight: 700,
  },
  documentList: { display: 'flex', flexWrap: 'wrap', gap: '8px' },
  documentGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(240px, 100%), 1fr))',
    gap: '12px',
  },
  documentCard: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    color: '#374151',
    background: '#ffffff',
    fontSize: '14px',
  },
  filterGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(180px, 100%), 1fr))',
    gap: '12px',
    alignItems: 'end',
  },
  rgBox: { border: '1px solid #bae6fd', borderRadius: '8px', padding: '10px', display: 'grid', gap: '4px', background: '#f0f9ff' },
  vaccineBox: { border: '1px solid #e5e7eb', borderRadius: '8px', padding: '10px', display: 'grid', gap: '4px', background: '#f9fafb' },
  vaccineSummary: {
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '4px',
    background: '#eff6ff',
    color: '#1e3a8a',
    fontSize: '14px',
  },
  vaccineDetailCard: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '5px',
    color: '#374151',
    background: '#ffffff',
    fontSize: '14px',
  },
  preferenceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))',
    gap: '10px',
  },
  preferenceCard: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#374151',
    background: '#ffffff',
    fontSize: '14px',
  },
  preferenceCardDisabled: {
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#4b5563',
    background: '#f9fafb',
    fontSize: '14px',
  },
  pushBox: {
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    color: '#1e3a8a',
    background: '#eff6ff',
    fontSize: '14px',
  },
  smallButton: {
    justifySelf: 'start',
    minHeight: '38px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    background: '#ffffff',
    color: '#334155',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 12px',
    fontSize: '13px',
  },
  smallDarkButton: {
    minHeight: '34px',
    border: '1px solid #1d4ed8',
    borderRadius: '8px',
    background: '#1d4ed8',
    color: '#ffffff',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 12px',
    fontSize: '13px',
  },
  uploadLabel: {
    justifySelf: 'start',
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '44px',
    border: '1px solid #1f6f43',
    borderRadius: '8px',
    background: '#ffffff',
    color: '#1f6f43',
    cursor: 'pointer',
    fontWeight: 700,
    padding: '0 12px',
    fontSize: '13px',
  },
  fileInput: { display: 'none' },
};
