import { PERMISSIONS } from '../../../utils/permissions';

export const educacaoAmbientalAdminNavigation = [
  { key: 'dashboard', label: 'Dashboard', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_VISUALIZAR },
  { key: 'conteudos', label: 'Conteudos', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_VISUALIZAR },
  { key: 'curadoria', label: 'Curadoria', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_CURADORIA_VISUALIZAR },
  { key: 'fontes', label: 'Fontes', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_FONTES_GERENCIAR },
  { key: 'referencias', label: 'Referencias', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_REFERENCIAS_GERENCIAR },
  { key: 'normas', label: 'Biblioteca normativa', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_NORMAS_GERENCIAR },
  { key: 'agenda', label: 'Agenda ambiental', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_AGENDA_GERENCIAR },
  { key: 'materiais', label: 'Materiais educativos', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_MATERIAIS_GERENCIAR },
  { key: 'trilhas', label: 'Trilhas', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_TRILHAS_GERENCIAR },
  { key: 'especies', label: 'Biodiversidade', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_BIODIVERSIDADE_GERENCIAR },
  { key: 'areas', label: 'Areas ambientais', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_AREAS_GERENCIAR },
  { key: 'programas', label: 'Programas e metas', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_PROGRAMAS_GERENCIAR },
  { key: 'faq', label: 'FAQ educativa', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_EDITAR },
  { key: 'base_ia', label: 'Base IA validada', permission: PERMISSIONS.EDUCACAO_AMBIENTAL_CURADORIA_VISUALIZAR },
];

export const educacaoAmbientalLayoutConfig = {
  moduleKey: 'educacao-ambiental',
  platformName: 'Plataforma SIGMA',
  brandBadge: 'EDUCA',
  brandSub: 'Modulo Educacao Ambiental da Plataforma SIGMA',
  pageTitle: 'Educacao Ambiental',
  pageSubtitle: 'Centro Municipal de Conhecimento Ambiental da SMAD',
  environmentLabel: 'Area interna SMAD',
  portalButtonLabel: 'Educacao Ambiental Demonstrativa',
  publicButtonLabel: 'Painel SIGMA',
  logoutButtonLabel: 'Sair',
  footerText: 'SMAD - Plataforma SIGMA / Educacao Ambiental',
  menuItems: educacaoAmbientalAdminNavigation,
  showPortalShortcut: true,
  showPublicShortcut: true,
  theme: {
    appBackground: '#eef7f3',
    mainBackground: '#eef7f3',
    contentBackground: 'linear-gradient(180deg, #eef7f3 0%, #f8fbfa 46%, #eef7f3 100%)',
    sidebarBackground: 'linear-gradient(180deg, #0d1b3d 0%, #175e4a 100%)',
    sidebarBorder: '#175e4a',
    sidebarDivider: 'rgba(255, 255, 255, 0.16)',
    sidebarShadow: '8px 0 24px rgba(13, 27, 61, 0.12)',
    brandBackground: '#198754',
    brandColor: '#ffffff',
    brandShadow: '0 10px 22px rgba(25, 135, 84, 0.24)',
    brandSubColor: '#dff7ec',
    footerColor: '#dff7ec',
    headerBackground: 'rgba(255, 255, 255, 0.94)',
    headerBorder: '#cfe8dc',
    headerShadow: '0 8px 24px rgba(23, 94, 74, 0.06)',
    titleColor: '#0d1b3d',
    subtitleColor: '#5f6f83',
    accent: '#198754',
    infoBackground: '#ecfdf3',
    infoBorder: '#c8ead5',
    infoColor: '#176a36',
    controlBackground: '#ffffff',
    controlBorder: '#cfe8dc',
    controlColor: '#0d1b3d',
    navBackground: 'rgba(255, 255, 255, 0.08)',
    navBorder: 'rgba(255, 255, 255, 0.14)',
    navColor: '#f4fff8',
    navActiveBackground: '#ffffff',
    navActiveBorder: '#ffffff',
    navActiveColor: '#176a36',
    navActiveShadow: '0 12px 24px rgba(0, 0, 0, 0.16)',
  },
};
