export const assistenteStyles = {
  section: {
    background: '#ffffff',
    border: '1px solid #d8e8f6',
    borderRadius: 8,
    padding: 'clamp(18px, 3vw, 28px)',
    boxShadow: '0 16px 36px rgba(13, 63, 143, 0.08)',
  },
  card: {
    border: '1px solid #e2edf8',
    borderRadius: 8,
    background: '#f8fbff',
    padding: 16,
  },
  cardWhite: {
    border: '1px solid #d8e8f6',
    borderRadius: 8,
    background: '#ffffff',
    padding: 16,
  },
  title: {
    margin: 0,
    fontSize: 26,
    lineHeight: 1.15,
    color: '#0d1b3d',
  },
  subtitle: {
    color: '#516984',
    lineHeight: 1.55,
    margin: '8px 0 0',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))',
    gap: 16,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(230px, 100%), 1fr))',
    gap: 14,
  },
  label: {
    display: 'grid',
    gap: 7,
    fontSize: 13,
    fontWeight: 800,
    color: '#0d1b3d',
  },
  input: {
    width: '100%',
    minHeight: 44,
    borderRadius: 8,
    border: '1px solid #bdd3ec',
    padding: '10px 12px',
    fontSize: 14,
    color: '#172033',
    background: '#ffffff',
  },
  textarea: {
    width: '100%',
    minHeight: 132,
    borderRadius: 8,
    border: '1px solid #bdd3ec',
    padding: '12px',
    fontSize: 15,
    lineHeight: 1.45,
    color: '#172033',
    background: '#ffffff',
    resize: 'vertical',
  },
  checkbox: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 9,
    minHeight: 42,
    border: '1px solid #d8e8f6',
    borderRadius: 8,
    padding: '10px 12px',
    background: '#ffffff',
    color: '#20324b',
    fontWeight: 700,
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  buttonPrimary: {
    minHeight: 44,
    borderRadius: 8,
    border: '1px solid #0f7a3b',
    background: 'linear-gradient(180deg, #1ca353 0%, #0f7a3b 100%)',
    color: '#ffffff',
    fontWeight: 850,
    padding: '0 16px',
    cursor: 'pointer',
    boxShadow: '0 12px 24px rgba(15, 122, 59, 0.2)',
  },
  buttonSecondary: {
    minHeight: 44,
    borderRadius: 8,
    border: '1px solid #bdd3ec',
    background: '#ffffff',
    color: '#0d3f8f',
    fontWeight: 800,
    padding: '0 16px',
    cursor: 'pointer',
  },
  badge: {
    display: 'inline-flex',
    width: 'fit-content',
    borderRadius: 999,
    padding: '6px 10px',
    fontSize: 12,
    fontWeight: 850,
    border: '1px solid #bdd3ec',
    background: '#eef6ff',
    color: '#0d3f8f',
  },
  list: {
    margin: '10px 0 0',
    paddingLeft: 20,
    color: '#20324b',
    lineHeight: 1.55,
  },
  warning: {
    border: '1px solid #f4c56a',
    background: '#fff8e7',
    borderRadius: 8,
    padding: 14,
    color: '#634000',
    fontWeight: 700,
  },
  success: {
    border: '1px solid #9bd7af',
    background: '#edf9f1',
    borderRadius: 8,
    padding: 14,
    color: '#0f5f2e',
    fontWeight: 750,
  },
};

export function attentionStyle(level) {
  const map = {
    baixo: { background: '#edf9f1', borderColor: '#bde7cc', color: '#0f7a3b' },
    medio: { background: '#fff8e7', borderColor: '#f4c56a', color: '#875300' },
    alto: { background: '#fff1f2', borderColor: '#fecdd3', color: '#be123c' },
  };

  return {
    ...assistenteStyles.badge,
    ...(map[level] || map.medio),
  };
}
