import { PERMISSIONS } from '../../../utils/permissions';

export const viveiroAdminNavigation = [
  { key: 'dashboard', label: 'Dashboard', permission: PERMISSIONS.VIVEIRO_DASHBOARD_VIEW },
  { key: 'especies', label: 'Espécies', permission: PERMISSIONS.VIVEIRO_ESPECIES_VIEW },
  { key: 'lotes', label: 'Lotes', permission: PERMISSIONS.VIVEIRO_LOTES_VIEW },
  { key: 'estoque', label: 'Estoque', permission: PERMISSIONS.VIVEIRO_ESTOQUE_VIEW },
  { key: 'solicitacoes', label: 'Solicitações', permission: PERMISSIONS.VIVEIRO_SOLICITACOES_VIEW },
  { key: 'entregas', label: 'Entregas', permission: PERMISSIONS.VIVEIRO_ENTREGAS_VIEW },
];

export const viveiroLayoutConfig = {
  moduleKey: 'viveiro',
  platformName: 'Plataforma SIGMA',
  brandBadge: 'VIVEIRO',
  brandSub: 'Módulo do Viveiro Municipal da Plataforma SIGMA',
  pageTitle: 'Viveiro Municipal',
  pageSubtitle: 'Gestão de espécies, lotes, estoque, solicitações e entregas',
  environmentLabel: 'Área interna SMAD',
  portalButtonLabel: 'Portal SIGMA',
  publicButtonLabel: 'Painel SIGMA',
  logoutButtonLabel: 'Sair',
  footerText: 'SMAD - Plataforma SIGMA / Viveiro Municipal',
  menuItems: viveiroAdminNavigation,
  showPortalShortcut: false,
  showPublicShortcut: false,
  theme: {
    appBackground: '#eef7f0',
    mainBackground: '#eef7f0',
    contentBackground: 'linear-gradient(180deg, #eef7f0 0%, #f8fbf9 42%, #eef7f0 100%)',
    sidebarBackground: 'linear-gradient(180deg, #0d1b3d 0%, #0f3d2e 100%)',
    sidebarBorder: '#0f3d2e',
    sidebarDivider: 'rgba(255, 255, 255, 0.16)',
    sidebarShadow: '8px 0 24px rgba(13, 27, 61, 0.12)',
    brandBackground: '#2e9e4b',
    brandColor: '#ffffff',
    brandShadow: '0 10px 22px rgba(46, 158, 75, 0.28)',
    brandSubColor: '#d7f5dd',
    footerColor: '#d7f5dd',
    headerBackground: 'rgba(255, 255, 255, 0.94)',
    headerBorder: '#d7eadc',
    headerShadow: '0 8px 24px rgba(23, 74, 45, 0.06)',
    titleColor: '#0d1b3d',
    subtitleColor: '#5f6f83',
    accent: '#2e9e4b',
    infoBackground: '#effaf2',
    infoBorder: '#cfe9d7',
    infoColor: '#176a36',
    controlBackground: '#ffffff',
    controlBorder: '#cfe0d4',
    controlColor: '#0d1b3d',
    navBackground: 'rgba(255, 255, 255, 0.08)',
    navBorder: 'rgba(255, 255, 255, 0.14)',
    navColor: '#f4fff7',
    navActiveBackground: '#ffffff',
    navActiveBorder: '#ffffff',
    navActiveColor: '#176a36',
    navActiveShadow: '0 12px 24px rgba(0, 0, 0, 0.16)',
  },
};
